### ISSUE TITLE
EDIT & DELETE ICONS DON'T APPEAR WHEN ADDING A NEW ITEM TO THE LIST

### ISSUE THREAD

**Issue by jhenry081** [jhenry081/projects-using-js#7]
As the project uses Bootstrap for the CSS, adding a new item to the list should also place the edit and delete icons in their respective places but they do not appear.  

## Tasks List
- [x] add to-do
- [x] delete to-do
- [ ] add edit & delete icons to every new item on to-do
- [ ] update to-do
- [ ] search to-do
- [ ] complete to-do
- [ ] incomplete to-do
- [ ] reset to-do list
- [ ] undo reset to-do list
- [ ] multiple to-do complete
- [ ] multiple delete to-do
- [ ] sort to-do list
